name: Feedback
description: Provide feedback related to an RFP process
title: "[Feedback]: "
labels: [feedback]

body:
  - type: input
    id: rfp-name
    attributes:
      label: "RFP Name"
      description: "Enter the name of the RFP you are providing feedback for."
      placeholder: "e.g., RFP-1234: Cloud Services"
    validations:
      required: true

  - type: dropdown
    id: stage
    attributes:
      label: "Stage"
      description: "Criteria or Evaluation"
      options:
        - "Select a stage..."
        - Criteria
        - Evaluation
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **📎 Upload the RFP Document**
        - Please attach the relevant RFP document below using the GitHub issue attachment feature.
        - Drag and drop the file or click the attachment icon when submitting this issue.

  - type: textarea
    id: feedback
    attributes:
      label: "Feedback"
      description: "Provide your detailed feedback."
      placeholder: "Describe your feedback in detail..."
    validations:
      required: true
